### ISSUE TITLE
Differing queries 

### ISSUE THREAD

**Issue by jounaidr** [PrincetonUniversity/jobstats#12]
Hi,

Thanks for this project, it is exactly what I was looking for for a similar HPC system. I have managed to setup and run the platform with Grafana, however it required changes to the queries (just syntactically) and looking at the other issues it appears there's some discrepancy with the exporter versions. I believe I was using the modified cgroups exporter provided, but to get it working I had to change the queries to what the metric label was displaying in Prometheus. I am attempting to consolidate the queries into the config file for our setup so its would be somewhat easier to change them in the future if we were to add new exporters or if the existing exporter queries change. Also i'm thinking the issues could be caused by my Prometheus config as what was in the docs was not working so I just made a basic one (i am new to Prometheus :p). Please feel free to close this if its not acceptable!

here is my prom config:
``

**Comment by plazonic** [comment]
Hello,

good to hear that you managed to get it working but it seems like you had some copy/paste problems? I do not see your configuration attached so not sure what you mean or what problem you had.

**Comment by jounaidr** [comment]
Ah yes sorry I updated the comment it should be there now! and thanks for the quick response!

**Comment by jounaidr** [comment]
and this is what I changed the queries to within jobstats:

```python
    def get_job_stats(self):
        # query CPU and Memory utilization data
        self.get_data('total_memory', "max_over_time(cgroup_memory_total_bytes{cgroup='/slurm_localhost/uid_0/job_%s', instance='localhost:9306', job='prometheus'}[%ds])")
        self.get_data('used_memory', "max_over_time(cgroup_memory_rss_bytes{cgroup='/slurm_localhost/uid_0/job_%s', instance='localhost:9306', job='prometheus'}[%ds])")
        self.get_data('total_time', "max_over_time(cgroup_cpu_total_seconds{cgroup='/slurm_localhost/uid_0/job_%s', instance='localhost:9306', job='prometheus'}[%ds])")
        self.get_data('cpus', "max_over_time(cgroup_cpus{cgroup='/slurm_localhost/uid_0/job_%s', instance='localhost:9306', job='prometheus'}[%ds])")
```

**Comment by plazonic** [comment]
You need the cluster label in your scrape_config - it is mentioned in our main README and I also expanded on it in issue #8 - we expect that to be added at collection time.

**Comment by jounaidr** [comment]
Ok thanks, I was having issues with the labels previously but I will try and update the issue, tysm :)

**Comment by jounaidr** [comment]
Hi, so I updated the prom config, after some syntax issues it is happy and running:

```yaml
global:
 scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
 external_labels:
  monitor: 'node-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
- job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
  scrape_interval: 5s

  file_sd_configs:
  - files:
    - "/root/prometheus-2.51.2.linux-amd64/localnodes.json"
  metric_relabel_configs:
  - source_labels:
    - __name__
    regex: "^go_.*"
    action: drop
```

and the nodes json:
```json
 [
   {
     "labels": {
       "cluster": "localcluster",
       "service": "compute"
     },
     "targets": [
       "localhost:9100",
       "localhost:9821",
       "localhost:9306"
     ]
   }
 ]
```

However it still is only working with the changes queries :/, just to confirm I am using the following cgroups exporter: https://github.com/treydock/cgroup_exporter/releases/tag/v0.9.1

I just saw there's a new release so ill try that as well
